version: 2

references:
  ## Workspaces
  workspace: &workspace
    ~/src

  ## Docker image configurations
  android_config: &android_config
    working_directory: *workspace
    docker:
      - image: circleci/android:api-29
    environment:
      TERM: dumb
      JVM_OPTS: -Xmx3200m

  ## Cache
  gradle_key: &gradle_key
    jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum "github-viewer/build.gradle" }}

  restore_gradle_cache: &restore_gradle_cache
    restore_cache:
      key: *gradle_key

  save_gradle_cache: &save_gradle_cache
    save_cache:
      key: *gradle_key
      paths:
        - ~/.gradle
        - ~/.m2

  android_dependencies: &android_dependencies
    run:
      name: Download Android Dependencies
      command: ./gradlew androidDependencies

  change_permissions: &change_permissions
    run:
      name: Change permissions
      command: sudo chmod +x ./gradlew

jobs:
  test:
    <<: *android_config
    steps:
      - checkout
      - *restore_gradle_cache
      - *change_permissions
      - *android_dependencies
      - *save_gradle_cache
      - run:
          name: Run Tests
          command: ./gradlew lint test detekt
      - store_artifacts:
          path: github-viewer/build/reports/
          destination: /reports/
      - store_test_results:
          path: github-viewer/build/test-results/
          destination: /test-results/

  build:
    <<: *android_config
    steps:
      - checkout
      - *restore_gradle_cache
      - *change_permissions
      - *android_dependencies
      - *save_gradle_cache
      - run:
          name: Build
          command: ./gradlew assembleFlowRelease
      - store_artifacts:
          path: github-viewer/build/outputs/apk/flow/release
          destination: /apk/

workflows:
  version: 2
  workflow:
    jobs:
      - test
      - build:
          requires:
            - test